### ISSUE TITLE
页面上添加自定义依赖功能

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/Use-iceWorks#12]
系统  win7
node V8.9.3

操作步骤
- 选择一个项目
- 点击项目中添加自定义依赖的按钮
- 弹出提示框，提示需要填入的文本格式为   name@Version
- 我随意填写了一串字符`asadads`
- 点击了确定按钮
- 页面代码逻辑貌似没有做内容正则匹配，直接去镜像源中找了，
- 过了几分钟，出现了错误弹窗

```bash
[2018-02-26 18:20:34.407] [debug] ipcRenderer npminstall [ 'asadads@latest', '--save' ]
[2018-02-26 18:20:54.259] [debug] npm ERR! code E404
[2018-02-26 18:20:54.259] [debug] npm
[2018-02-26 18:20:54.259] [debug] ERR! 404 Not Found: asadads@latest
[2018-02-26 18:21:16.691] [debug] 
[2018-02-26 18:21:16.691] [debug] npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-02-26T10_20_54_261Z-debug.log
[2018-02-26 18:21:16.712] [error] 安装依赖失败 F:\documentbak\2_26\bak\melon_cms [ 'asadads@latest', '--save' ]
[2018-02-26 18:21:16.712] [error] Error: runcmd
    at ChildProcess.c.on.e (D:\Users\Administrator\AppData\Local\Programs\Iceworks\resources\app\main\npm.js:1:782)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

**Comment by mowatermelon** [comment]
个人思考

- 这边逻辑好像是认为只填写`npm`包名就可以，后面的版本号，默认值是`latest`
- 我认为这个逻辑应该是，首先严格按照正则进行匹配格式，不通过的，不去请求网络资源进行寻找
- 如果通过了正则匹配，但是版本号不对的，可以使用默认值 `latest`

**Comment by mowatermelon** [comment]
![图片](https://dn-coding-net-production-pp.qbox.me/ceb3512f-1fd7-41b1-845d-41a15d29cfcb.png)


这个问题还在


没有做正则检测   直接就去安装了


```cmd

[2018-04-11 18:13:32.914] [debug] npm install 545645645646@latest --save --no-package-lock --scripts-prepend-node-path=auto F:\documentbak\4_11\bak\waterAnalytical
[2018-04-11 18:13:46.835] [debug] npm
[2018-04-11 18:13:46.837] [debug] ERR! code E404
[2018-04-11 18:13:46.839] [debug] npm
[2018-04-11 18:13:46.841] [debug] ERR! 404 Not Found: 545645645646@latest
```
