### ISSUE TITLE
项目源码下执行启动启动不成功

### ISSUE THREAD

**Issue by mowatermelon** [mowatermelon/Use-iceWorks#16]
```bash
$ node main/index.js
module.js:538
    throw err;
    ^

Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (X:xx\node_modules\electron-settings\lib\settings.js:11:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by mowatermelon** [comment]
> 修改`package.json`，添加“script”

```json
  "scripts": {
    "start": "electron ./main/index.js",
    "package:linux32": "electron-packager ./ Iceworks --platform=linux --arch=ia32 ~/Desktop/Iceworks --version 0.30.2 --overwrite --icon=./static/touchbar/logo.png",
    "package:linux64": "electron-packager ./ Iceworks --platform=linux --arch=x64 ~/Desktop/Iceworks --version 0.30.2 --overwrite --icon=./static/touchbar/logo.png",
    "package:mac": "electron-packager ./ Iceworks --platform=darwin --arch=x64 ~/Desktop/Iceworks --version 0.30.2 --overwrite --icon=./static/touchbar/logo.png",
    "package:win32": "electron-packager ./ Iceworks --platform=win32 --arch=ia32 ~/Desktop/Iceworks --version 0.30.2 --overwrite --icon=./static/touchbar/logo.png",
    "package:win64": "electron-packager ./ Iceworks --platform=win32 --out=./dist --arch=x64 ~/Desktop/Iceworks --version 0.30.2 --overwrite --icon=./static/touchbar/logo.png"
  },
```

> 修改`package.json`，添加`electron`依赖

```json
  "dependencies": {
    "electron": "~1.7.8"
    ...
  }
```

> 运行命令行，出现了一个只有menu的window，但是这个menu比正式版多一个开发调试按钮

```bash
$ npm run start

> iceworks-desktop@1.1.1 start X:\XXX\Use-iceWorks
> electron ./main/index.js


[info] process.version: v7.9.0
[info] process.platform: win32
[info] process.arch: x64
[info] process.versions.modules: 54
[info] shortcutKey register success CommandOrControl+alt+P
[info] iceworks ipc started at 8000
[debug] node version: v8.9.3
```

**Comment by mowatermelon** [comment]
> 执行打包命令，打包成功了，可是点击软件运行失败

![image](https://user-images.githubusercontent.com/18508817/37456058-7c1ad530-2879-11e8-8095-31ae6f3246ae.png)

**Comment by mowatermelon** [comment]
> 我将ice实际的项目缓存复制到开发项目文件夹，这边有一个install.exe，我发现点击这个之后，会检测到开发的Electron桌面实际在运行，然后进行提示，自动关闭了我调试进程，然后进行了安装

![图片](https://dn-coding-net-production-pp.qbox.me/12767137-fa0a-4fc2-8bad-dfacc2a03e55.png)

**Comment by mowatermelon** [comment]
> 安装完成自动打开了调试的客户端

![图片](https://dn-coding-net-production-pp.qbox.me/3c2a8541-1e3e-4773-bb6b-28253a7db2fe.png)

**Comment by mowatermelon** [comment]
看了一下感觉ice桌面端主要就是分了三种情况，一种是mac，一种是win，一种是dev

```javascript
const {
	Menu: e,
	shell: l,
	BrowserWindow: t
} = require("electron"), o = require("electron-log"), {
	isMac: a,
	isWin: r,
	isDev: s
} = require("./shared"), c = require("./autoUpdater"), i = require("./helper/sendToWebContents"), {
	openAboutWindow: n
} = require("./windowList");

function b(e, {
	state: l,
	title: t,
	url: o
}) {
	i(e.home, "router.push", {
		state: l,
		title: t,
		url: o
	}), e.home.isVisible() ? e.home.focus() : e.home.show()
}
exports.trayMenu = ((l, t, o) => {
	const a = [{
		label: "\u5173\u4e8e Iceworks"
	}, {
		type: "separator"
	}, {
		label: "\u8bbe\u7f6e",
		click() {
			b(t, {
				state: null,
				title: "Settings",
				url: "/settings"
			})
		}
	}, {
		type: "separator"
	}, {
		abel: "\u9000\u51fa",
		role: "quit",
		accelerator: "Cmd+Q"
	}];
	return e.buildFromTemplate(a)
}), exports.appMenu = ((i, p) => {
	const u = [{
		label: "\u6587\u6863",
		click() {
			l.openExternal("https://alibaba.github.io/ice")
		}
	}, {
		label: "Github",
		click() {
			l.openExternal("https://github.com/alibaba/ice")
		}
	}, {
		type: "separator"
	}, {
		label: "\u53cd\u9988\u95ee\u9898",
		click() {
			l.openExternal("https://github.com/alibaba/ice/issues/new?labels=iceworks")
		}
	}, {
		type: "separator"
	}, {
		label: "\u67e5\u770b\u8bb8\u53ef\u8bc1",
		click() {
			l.openExternal("https://github.com/alibaba/ice/blob/master/LICENSE")
		}
	}, {
		label: "\u9690\u79c1\u58f0\u660e",
		click() {
			l.openExternal("https://terms.alicdn.com/legal-agreement/terms/suit_bu1_taobao/suit_bu1_taobao201703241622_61002.html")
		}
	}, {
		type: "separator"
	}, {
		label: "\u5207\u6362\u5f00\u53d1\u4eba\u5458\u5de5\u5177",
		accelerator: a ? "Alt+Command+I" : "Ctrl+Shift+I",
		click(e, l) {
			l && l.toggleDevTools()
		}
	}, {
		label: "\u67e5\u770b\u8fd0\u884c\u65e5\u5fd7",
		click() {
			const e = o.transports.file.findLogPath(i.getName());
			l.showItemInFolder(e)
		}
	}];
	r && (u.push({
		type: "separator"
	}), u.push({
		label: "\u68c0\u67e5\u66f4\u65b0...",
		click() {
			c.show()
		}
	}), u.push({
		type: "separator"
	}), u.push({
		label: "\u5173\u4e8e",
		click() {
			n()
		}
	}));
	const m = [{
		label: "\u7f16\u8f91",
		submenu: [{
			label: "\u64a4\u9500",
			role: "undo",
			accelerator: "CommandOrControl+Z"
		}, {
			label: "\u91cd\u505a",
			role: "redo",
			accelerator: "CommandOrControl+Shift+Z"
		}, {
			type: "separator"
		}, {
			label: "\u526a\u5207",
			role: "cut",
			accelerator: "CommandOrControl+X"
		}, {
			label: "\u590d\u5236",
			role: "copy",
			accelerator: "CommandOrControl+C"
		}, {
			label: "\u7c98\u8d34",
			role: "paste",
			accelerator: "CommandOrControl+V"
		}, {
			label: "\u9009\u62e9\u5168\u90e8",
			role: "selectall",
			accelerator: "CommandOrControl+A"
		}]
	}, {
		label: "\u7a97\u53e3",
		submenu: [{
			label: "\u5173\u95ed",
			role: "close",
			accelerator: "CommandOrControl+W"
		}, {
			label: "\u6700\u5c0f\u5316",
			role: "minimize",
			accelerator: "CommandOrControl+M"
		}, {
			label: "\u7f29\u653e",
			role: "zoom"
		}, {
			label: "\u5207\u6362\u5168\u5c4f",
			role: "togglefullscreen",
			accelerator: a ? "Ctrl+Command+F" : "F11"
		}, {
			type: "separator"
		}, {
			label: "\u5168\u90e8\u7f6e\u4e8e\u9876\u5c42",
			role: "front"
		}]
	}, {
		label: "\u5e2e\u52a9",
		submenu: u
	}];
	if (a) {
		const e = i.getName();
		m.unshift({
			label: e,
			submenu: [{
				label: "\u5173\u4e8e Iceworks",
				click() {
					n()
				}
			}, {
				type: "separator"
			}, {
				label: "\u68c0\u67e5\u66f4\u65b0...",
				click() {
					c.show()
				}
			}, {
				type: "separator"
			}, {
				label: "\u8bbe\u7f6e",
				accelerator: "CmdOrCtrl+,",
				click() {
					b(p, {
						state: null,
						title: "Settings",
						url: "/settings"
					})
				}
			}, {
				type: "separator"
			}, {
				label: "\u670d\u52a1",
				role: "services",
				submenu: []
			}, {
				type: "separator"
			}, {
				label: "\u9690\u85cf Iceworks",
				role: "hide"
			}, {
				label: "\u9690\u85cf\u5176\u4ed6",
				role: "hideothers"
			}, {
				label: "\u5168\u90e8\u663e\u793a",
				role: "unhide"
			}, {
				type: "separator"
			}, {
				label: "\u9000\u51fa Iceworks",
				role: "quit"
			}]
		})
	}
	s && m.push({
		label: "\u5f00\u53d1\u8c03\u8bd5",
		submenu: [{
			label: "Reload",
			accelerator: "CmdOrCtrl+R",
			click(e, l) {
				l && (1 === l.id && t.getAllWindows().forEach(e => {
					e.id > 1 && e.close()
				}), l.reload())
			}
		}, {
			label: "Toggle Developer Tools",
			accelerator: a ? "Alt+Command+I" : "Ctrl+Shift+I",
			click(e, l) {
				l && l.toggleDevTools()
			}
		}]
	});
	const h = e.buildFromTemplate(m);
	e.setApplicationMenu(h)
});
```

**Comment by mowatermelon** [comment]
启动成功啦，啦啦啦啦啦啦啦

![图片](https://dn-coding-net-production-pp.qbox.me/ffd18219-7437-4a22-b6c6-b553537b856c.png)

![图片](https://dn-coding-net-production-pp.qbox.me/4c019a60-bf35-411a-bc75-1b7e7d892a56.png)

![图片](https://dn-coding-net-production-pp.qbox.me/3899707e-8e92-46a1-a42b-143c71538e73.png)
